/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dav(props) {
  const { nodes, materials } = useGLTF("/4D SUBKIT PROINDECSA.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQ_ARD-geom002"].geometry}
          material={materials["TQ_ARD_front.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQ_ARD-geom002_1"].geometry}
          material={materials["TQ_ARD_back.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["TQ_ARD-geom002_2"].geometry}
          material={materials["TQ_ARD_edge.002"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/4D SUBKIT PROINDECSA.gltf");
